### ISSUE TITLE
[Implementation] Mobile landscape mode card alignment issue

### ISSUE THREAD

**Issue by murthyanish** [niyasrad/Xylium#25]
**Description**
- When on mobile, turning to landscape mode makes the cards align incorrectly. They get left adjusted.

**Insight**
- Perhaps force a centre align for cards in home. Make the pairs of cards an element (or frame) and centre align them.

**Screenshots**
![Screenshot_20230508-212707](https://user-images.githubusercontent.com/20863211/236872240-fcb0df2d-69bf-42ba-8b26-3a52660f2642.png)

**Comment by murthyanish** [comment]
![Screenshot_20230510-194514](https://github.com/niyasrad/Xylium/assets/20863211/db7914a2-cf98-4946-81e5-35413455867e)
![Screenshot_20230510-194503](https://github.com/niyasrad/Xylium/assets/20863211/d9adac69-58ef-4640-8203-0fb48234cd13)
Issue still ongoing

**Comment by niyasrad** [comment]
I was thinking, let's say a person played maximum one game at a time. their recents would look like this 

![image](https://github.com/niyasrad/Xylium/assets/84234554/c8409ea5-4ce3-4f0a-8e99-332036cc7d5a)
