### ISSUE TITLE
[Implementation] Sort list of owned games by play time

### ISSUE THREAD

**Issue by murthyanish** [niyasrad/Xylium#30]
**Description**
- The current list of owned games is sorted alphabetically, however this doesn't give a good idea of what kind of games a person plays. It would be preferable to have it he sorted by play time.

**Insight**
- Modify the sort to use play time

**Comment by murthyanish** [comment]
Edit to the original problem to understand the current situation better: the current sort is based on either steam game ID, or release date.

**Comment by niyasrad** [comment]
Noted. Do you believe sorting the friends is also an important thing?
