### ISSUE TITLE
[Implementation] Add account recovery options

### ISSUE THREAD

**Issue by murthyanish** [niyasrad/Xylium#34]
**Description**
In case a user has trouble logging in, they currently have no option to reset their password.

**Insight**
Consider adding email as a required input during user creation and have password reset requests send an email to the registered email.

**Comment by niyasrad** [comment]
This should be regarded and implemented based on two potential PRs.

- One is the implementation of E-mail with the account generation (Schema edit, option to verify account)
- Forgot Password section in the login page, making them send email with a link to get a token on the redirect page, with a timeout system. New page will have them enter their new password
