### ISSUE TITLE
[Implementation] Percentile Miscalculation

### ISSUE THREAD

**Issue by Vaish24navi** [niyasrad/Xylium#57]
**Description**
The current percentile values generated over the settings page, isn't accurate.

**Insight**
The account with the least value, seemed to be in 33.3% , while it must be 0%

**Screenshots**
![image](https://github.com/niyasrad/Xylium/assets/76160783/c93e78ed-0fdb-48bb-9ff4-5db1022b8e31)

**Comment by niyasrad** [comment]
Great insight. I'll assign you for this one~

**Comment by niyasrad** [comment]
Good work!
